### ISSUE TITLE
后台运行 会导致segment fault

### ISSUE THREAD

**Issue by BlackLuny** [vnt-dev/vnt#19]
nohup ./vnt-cli xxxx & 会导致segment fault

具体是，执行几分钟之后，就会崩溃，ps -ef 显示segment fault.
环境是ubuntu 20.04
前台运行不会崩溃。

**Comment by lbl8603** [comment]
使用的是什么版本的vnt

**Comment by BlackLuny** [comment]
> 使用的是什么版本的vnt
目前的最新版本

**Comment by lbl8603** [comment]
可以加参数-c，或者用1.2.5版本

**Comment by BlackLuny** [comment]
使用1.2.5还是有问题，隔一段时间之后就会退出。同时添加了-c，并且使用最新的代码编译的vnt-cli

**Comment by lbl8603** [comment]
可以用主分支上最新的代码编译debug版本看看吗，这样会有更多错误信息
