### ISSUE TITLE
这个是一定要用root权限才能运行么, 可不可以用普通用户启动?

### ISSUE THREAD

**Issue by yutent** [vnt-dev/vnt#50]

**Comment by lbl8603** [comment]
创建虚拟网卡要root权限

**Comment by yutent** [comment]
哦

**Comment by lbl8603** [comment]
你能帮忙测试不需要root权限的版本吗

**Comment by yutent** [comment]
可以, 我明天上班之后, 试一下

**Comment by yutent** [comment]
> 你能帮忙测试不需要root权限的版本吗

![image](https://github.com/lbl8603/vnt/assets/11972650/172d4761-e96d-4b10-b4ef-6642a7a4cf1b)


看的到机器, 但是IP不通

**Comment by lbl8603** [comment]
把两边的启动参数和输出信息都发出来看看

**Comment by yutent** [comment]
都删除完了, 下次吧

**Comment by lbl8603** [comment]
应该是参数没用对，再看看使用说明吧 [vn-link](https://github.com/lbl8603/vnt/tree/1.2.x/vn-link-cli#readme)
