### ISSUE TITLE
windows下必须要管理员权限才能运行吗，域内主机无管理员权限···

### ISSUE THREAD

**Issue by handbye** [vnt-dev/vnt#52]

**Comment by lbl8603** [comment]
要管理员权限才能开启虚拟网卡

**Comment by lbl8603** [comment]
有兴趣帮忙测试不需要管理员权限的版本吗

**Comment by handbye** [comment]
> 有兴趣帮忙测试不需要管理员权限的版本吗

可以的，请发我

**Comment by lbl8603** [comment]
提供邮箱地址，或者进群联系我

**Comment by handbye** [comment]
测试成功，可以正常使用，下面两张图是前后对比
![image](https://github.com/lbl8603/vnt/assets/26617058/3c9fa344-f6cf-41ac-b5a6-feffe6ea16ba)
![image](https://github.com/lbl8603/vnt/assets/26617058/e65e591e-a584-46f2-8d99-e21d636a2bfb)
