### ISSUE TITLE
【功能请求】佬，服务端使用 ws 套 cdn 时可否搞个优选 IP

### ISSUE THREAD

**Issue by SGN-EARTH** [vnt-dev/vnt#66]
这个项目 https://github.com/zanjie1999/tcp-over-websocket 使用 tcping 根据 DNS TTL 更新服务端 IP ，可以参考一波吗→_→
![2024-08-02_104338](https://github.com/user-attachments/assets/cb5cc3b4-030a-470a-9edb-313904fbb538)

**Comment by vnt-dev** [comment]
因为现在不同vnts数据是隔离的，所以做这个好像意义不大，等后面有vnts集群了考虑做吧

**Comment by SGN-EARTH** [comment]
好的
