### ISSUE TITLE
加了大写W的加密参数，如果服务端重置了，不重启客户端，一直重连会连不上

### ISSUE THREAD

**Issue by muziling** [vnt-dev/vnt#92]
服务端重装系统了，服务端再启动起来，客户端断线会一直重新连接，但永远连不上
重启客户端后，重新得到新的指纹才能连上。

服务端和客户端之间能否加个通知， 服务端通知客户端用新的指纹连接。

使用场景是客户端在异地内网，服务端重装后，没办法连到远程去重启客户端。

**Comment by vnt-dev** [comment]
有说明这种情况，服务端密钥变化了不能自动重连

**Comment by muziling** [comment]
是服务端自动生成的
public_key.pem
private_key.pem
变了，所以没办法重连上去吗？

我没有加finger参数

**Comment by vnt-dev** [comment]
是的，出于安全考虑，private_key变了会拒绝重连，因为客户端无法确认服务器的身份
